version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  logstash:
    image: logstash:latest
    volumes:
      - $PWD/config-dir:/config-dir
      - $PWD/logs:/logs
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    command: logstash -f /config-dir/logstash.conf
  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch