version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.106
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "filebeat_logs:1:1"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka
    volumes:
      - /etc/localtime:/etc/localtime:ro

  filebeat :
    image: elastic/filebeat:7.9.2
    user: root
    container_name: filebeat
    # links:
    #   - kafka:kafka
    depends_on:
      - kafka
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /var/run/docker.sock:/host_docker/docker.sock
      # - /var/lib/docker:/host_docker/var/lib/docker
      - ./filebeat_pipeline/data:/tmp/data
      - ./filebeat_pipeline/log:/usr/share/filebeat/mylog
      - ./filebeat_pipeline/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # stdin_open: true
    # tty: true
    # network_mode: bridge
    # deploy:
    #   mode: global
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "50"